import GModLua

/// Native GLua animation constants used by the bundled Base, Sandbox, and
/// Trouble in Terrorist Town Lua corpora.
///
/// Values are taken from the public Garry's Mod enum reference rather than
/// inferred from declaration order:
/// - https://wiki.facepunch.com/gmod/Enums/ACT
/// - https://wiki.facepunch.com/gmod/Enums/PLAYER
/// - https://wiki.facepunch.com/gmod/Enums/PLAYERANIMEVENT
/// - https://wiki.facepunch.com/gmod/Enums/GESTURE_SLOT
public enum GMLuaAnimationEnums {
    /// Exact ACT values statically referenced by the currently bundled
    /// Base/Sandbox/TTT Lua files. This is deliberately named as a corpus
    /// coverage set; it does not claim that every engine ACT is implemented.
    public static let activityConstantsRequiredByBundledGamemodes: [String: Int] = [
        "ACT_COVER_LOW": 5,
        "ACT_COVER_LOW_RPG": 351,
        "ACT_COVER_PISTOL_LOW": 301,
        "ACT_COVER_SMG1_LOW": 302,
        "ACT_CROUCHIDLE_AGITATED": 104,
        "ACT_CROUCHIDLE_AIM_STIMULATED": 103,
        "ACT_CROUCHIDLE_STIMULATED": 102,
        "ACT_GESTURE_RANGE_ATTACK_AR2": 304,
        "ACT_GESTURE_RANGE_ATTACK_PISTOL": 312,
        "ACT_GESTURE_RANGE_ATTACK_SHOTGUN": 311,
        "ACT_GESTURE_RANGE_ATTACK_SMG1": 308,
        "ACT_GESTURE_RANGE_ATTACK1": 137,
        "ACT_GESTURE_RELOAD": 382,
        "ACT_GESTURE_RELOAD_PISTOL": 383,
        "ACT_GESTURE_RELOAD_SHOTGUN": 385,
        "ACT_GESTURE_RELOAD_SMG1": 384,
        "ACT_GMOD_GESTURE_AGREE": 1_610,
        "ACT_GMOD_GESTURE_BECON": 1_611,
        "ACT_GMOD_GESTURE_BOW": 1_612,
        "ACT_GMOD_GESTURE_DISAGREE": 1_613,
        "ACT_GMOD_GESTURE_ITEM_DROP": 2_021,
        "ACT_GMOD_GESTURE_ITEM_GIVE": 2_020,
        "ACT_GMOD_GESTURE_ITEM_PLACE": 2_022,
        "ACT_GMOD_GESTURE_WAVE": 1_615,
        "ACT_GMOD_IN_CHAT": 2_019,
        "ACT_GMOD_NOCLIP_LAYER": 1_959,
        "ACT_GMOD_TAUNT_CHEER": 1_620,
        "ACT_HL2MP_GESTURE_RELOAD_AR2": 1_813,
        "ACT_HL2MP_GESTURE_RELOAD_CAMERA": 1_679,
        "ACT_HL2MP_GESTURE_RELOAD_CROSSBOW": 1_873,
        "ACT_HL2MP_GESTURE_RELOAD_DUEL": 1_853,
        "ACT_HL2MP_GESTURE_RELOAD_FIST": 1_966,
        "ACT_HL2MP_GESTURE_RELOAD_GRENADE": 1_843,
        "ACT_HL2MP_GESTURE_RELOAD_KNIFE": 1_981,
        "ACT_HL2MP_GESTURE_RELOAD_MAGIC": 1_659,
        "ACT_HL2MP_GESTURE_RELOAD_MELEE": 1_883,
        "ACT_HL2MP_GESTURE_RELOAD_MELEE2": 2_001,
        "ACT_HL2MP_GESTURE_RELOAD_PASSIVE": 1_991,
        "ACT_HL2MP_GESTURE_RELOAD_PHYSGUN": 1_863,
        "ACT_HL2MP_GESTURE_RELOAD_PISTOL": 1_793,
        "ACT_HL2MP_GESTURE_RELOAD_REVOLVER": 1_669,
        "ACT_HL2MP_GESTURE_RELOAD_RPG": 1_833,
        "ACT_HL2MP_GESTURE_RELOAD_SHOTGUN": 1_823,
        "ACT_HL2MP_GESTURE_RELOAD_SLAM": 1_893,
        "ACT_HL2MP_GESTURE_RELOAD_SMG1": 1_803,
        "ACT_HL2MP_IDLE": 1_777,
        "ACT_HL2MP_IDLE_AR2": 1_807,
        "ACT_HL2MP_IDLE_CAMERA": 1_673,
        "ACT_HL2MP_IDLE_CROSSBOW": 1_867,
        "ACT_HL2MP_IDLE_DUEL": 1_847,
        "ACT_HL2MP_IDLE_FIST": 1_960,
        "ACT_HL2MP_IDLE_GRENADE": 1_837,
        "ACT_HL2MP_IDLE_KNIFE": 1_975,
        "ACT_HL2MP_IDLE_MAGIC": 1_653,
        "ACT_HL2MP_IDLE_MELEE": 1_877,
        "ACT_HL2MP_IDLE_MELEE2": 1_995,
        "ACT_HL2MP_IDLE_PASSIVE": 1_985,
        "ACT_HL2MP_IDLE_PHYSGUN": 1_857,
        "ACT_HL2MP_IDLE_PISTOL": 1_787,
        "ACT_HL2MP_IDLE_REVOLVER": 1_663,
        "ACT_HL2MP_IDLE_RPG": 1_827,
        "ACT_HL2MP_IDLE_SHOTGUN": 1_817,
        "ACT_HL2MP_IDLE_SLAM": 1_887,
        "ACT_HL2MP_IDLE_SMG1": 1_797,
        "ACT_HL2MP_JUMP_SLAM": 1_894,
        "ACT_HL2MP_RUN": 1_779,
        "ACT_HL2MP_RUN_PISTOL": 1_789,
        "ACT_IDLE": 1,
        "ACT_IDLE_AGITATED": 79,
        "ACT_IDLE_AIM_AGITATED": 92,
        "ACT_IDLE_AIM_RELAXED": 90,
        "ACT_IDLE_AIM_RIFLE_STIMULATED": 336,
        "ACT_IDLE_AIM_STEALTH": 93,
        "ACT_IDLE_AIM_STIMULATED": 91,
        "ACT_IDLE_ANGRY": 76,
        "ACT_IDLE_ANGRY_PISTOL": 323,
        "ACT_IDLE_ANGRY_RPG": 350,
        "ACT_IDLE_ANGRY_SHOTGUN": 324,
        "ACT_IDLE_ANGRY_SMG1": 321,
        "ACT_IDLE_PISTOL": 322,
        "ACT_IDLE_RELAXED": 77,
        "ACT_IDLE_RPG": 349,
        "ACT_IDLE_RPG_RELAXED": 348,
        "ACT_IDLE_SHOTGUN_AGITATED": 341,
        "ACT_IDLE_SHOTGUN_RELAXED": 339,
        "ACT_IDLE_SHOTGUN_STIMULATED": 340,
        "ACT_IDLE_SMG1": 320,
        "ACT_IDLE_SMG1_RELAXED": 330,
        "ACT_IDLE_SMG1_STIMULATED": 331,
        "ACT_IDLE_STEALTH": 80,
        "ACT_IDLE_STEALTH_PISTOL": 325,
        "ACT_IDLE_STIMULATED": 78,
        "ACT_INVALID": -1,
        "ACT_LAND": 33,
        "ACT_MP_ATTACK_CROUCH_PRIMARYFIRE": 1_015,
        "ACT_MP_ATTACK_STAND_PRIMARYFIRE": 1_011,
        "ACT_MP_CROUCH_IDLE": 991,
        "ACT_MP_CROUCHWALK": 999,
        "ACT_MP_JUMP": 1_001,
        "ACT_MP_RELOAD_CROUCH": 1_028,
        "ACT_MP_RELOAD_STAND": 1_025,
        "ACT_MP_RUN": 996,
        "ACT_MP_STAND_IDLE": 990,
        "ACT_MP_SWIM": 1_006,
        "ACT_MP_SWIM_IDLE": 1_010,
        "ACT_MP_WALK": 997,
        "ACT_RANGE_AIM_AR2_LOW": 300,
        "ACT_RANGE_AIM_LOW": 297,
        "ACT_RANGE_AIM_PISTOL_LOW": 299,
        "ACT_RANGE_AIM_SMG1_LOW": 298,
        "ACT_RANGE_ATTACK_AR2": 279,
        "ACT_RANGE_ATTACK_PISTOL": 289,
        "ACT_RANGE_ATTACK_PISTOL_LOW": 290,
        "ACT_RANGE_ATTACK_RPG": 295,
        "ACT_RANGE_ATTACK_SHOTGUN": 287,
        "ACT_RANGE_ATTACK_SHOTGUN_LOW": 288,
        "ACT_RANGE_ATTACK_SMG1": 284,
        "ACT_RANGE_ATTACK_SMG1_LOW": 285,
        "ACT_RANGE_ATTACK1": 16,
        "ACT_RANGE_ATTACK1_LOW": 18,
        "ACT_READINESS_AGITATED_TO_STIMULATED": 420,
        "ACT_READINESS_PISTOL_AGITATED_TO_STIMULATED": 424,
        "ACT_READINESS_PISTOL_RELAXED_TO_STIMULATED": 422,
        "ACT_READINESS_PISTOL_RELAXED_TO_STIMULATED_WALK": 423,
        "ACT_READINESS_PISTOL_STIMULATED_TO_RELAXED": 425,
        "ACT_READINESS_RELAXED_TO_STIMULATED": 418,
        "ACT_READINESS_RELAXED_TO_STIMULATED_WALK": 419,
        "ACT_READINESS_STIMULATED_TO_RELAXED": 421,
        "ACT_RELOAD": 66,
        "ACT_RELOAD_LOW": 69,
        "ACT_RELOAD_PISTOL": 376,
        "ACT_RELOAD_PISTOL_LOW": 377,
        "ACT_RELOAD_SHOTGUN": 380,
        "ACT_RELOAD_SHOTGUN_LOW": 381,
        "ACT_RELOAD_SMG1": 378,
        "ACT_RELOAD_SMG1_LOW": 379,
        "ACT_RUN": 10,
        "ACT_RUN_AGITATED": 88,
        "ACT_RUN_AIM": 11,
        "ACT_RUN_AIM_AGITATED": 100,
        "ACT_RUN_AIM_PISTOL": 372,
        "ACT_RUN_AIM_RELAXED": 98,
        "ACT_RUN_AIM_RIFLE": 363,
        "ACT_RUN_AIM_RIFLE_STIMULATED": 338,
        "ACT_RUN_AIM_SHOTGUN": 368,
        "ACT_RUN_AIM_STEALTH": 101,
        "ACT_RUN_AIM_STEALTH_PISTOL": 375,
        "ACT_RUN_AIM_STIMULATED": 99,
        "ACT_RUN_CROUCH": 12,
        "ACT_RUN_CROUCH_AIM": 13,
        "ACT_RUN_CROUCH_AIM_RIFLE": 365,
        "ACT_RUN_CROUCH_RIFLE": 364,
        "ACT_RUN_CROUCH_RPG": 355,
        "ACT_RUN_PISTOL": 370,
        "ACT_RUN_RELAXED": 86,
        "ACT_RUN_RIFLE": 362,
        "ACT_RUN_RIFLE_RELAXED": 333,
        "ACT_RUN_RIFLE_STIMULATED": 335,
        "ACT_RUN_RPG": 353,
        "ACT_RUN_STEALTH": 89,
        "ACT_RUN_STEALTH_PISTOL": 366,
        "ACT_RUN_STIMULATED": 87,
        "ACT_SHOTGUN_RELOAD_FINISH": 268,
        "ACT_SHOTGUN_RELOAD_START": 267,
        "ACT_SIGNAL_FORWARD": 53,
        "ACT_SIGNAL_GROUP": 54,
        "ACT_SIGNAL_HALT": 55,
        "ACT_VM_DRAW_SILENCED": 497,
        "ACT_VM_HITCENTER": 191,
        "ACT_VM_IDLE": 174,
        "ACT_VM_MISSCENTER": 197,
        "ACT_VM_PRIMARYATTACK": 181,
        "ACT_VM_PRIMARYATTACK_SILENCED": 493,
        "ACT_VM_PULLPIN": 180,
        "ACT_VM_RELOAD": 183,
        "ACT_VM_RELOAD_SILENCED": 494,
        "ACT_VM_SECONDARYATTACK": 182,
        "ACT_VM_THROW": 179,
        "ACT_WALK": 6,
        "ACT_WALK_AGITATED": 84,
        "ACT_WALK_AIM": 7,
        "ACT_WALK_AIM_AGITATED": 96,
        "ACT_WALK_AIM_PISTOL": 371,
        "ACT_WALK_AIM_RELAXED": 94,
        "ACT_WALK_AIM_RIFLE": 359,
        "ACT_WALK_AIM_RIFLE_STIMULATED": 337,
        "ACT_WALK_AIM_SHOTGUN": 367,
        "ACT_WALK_AIM_STEALTH": 97,
        "ACT_WALK_AIM_STEALTH_PISTOL": 374,
        "ACT_WALK_AIM_STIMULATED": 95,
        "ACT_WALK_CROUCH": 8,
        "ACT_WALK_CROUCH_AIM": 9,
        "ACT_WALK_CROUCH_AIM_RIFLE": 361,
        "ACT_WALK_CROUCH_RIFLE": 360,
        "ACT_WALK_CROUCH_RPG": 354,
        "ACT_WALK_PISTOL": 369,
        "ACT_WALK_RELAXED": 82,
        "ACT_WALK_RIFLE": 358,
        "ACT_WALK_RIFLE_RELAXED": 332,
        "ACT_WALK_RIFLE_STIMULATED": 334,
        "ACT_WALK_RPG": 352,
        "ACT_WALK_STEALTH": 85,
        "ACT_WALK_STEALTH_PISTOL": 373,
        "ACT_WALK_STIMULATED": 83
    ]

    public static let playerConstants: [String: Int] = [
        "PLAYER_IDLE": 0,
        "PLAYER_WALK": 1,
        "PLAYER_JUMP": 2,
        "PLAYER_SUPERJUMP": 3,
        "PLAYER_DIE": 4,
        "PLAYER_ATTACK1": 5,
        "PLAYER_IN_VEHICLE": 6,
        "PLAYER_RELOAD": 7,
        "PLAYER_START_AIMING": 8,
        "PLAYER_LEAVE_AIMING": 9
    ]

    public static let playerAnimationEventConstants: [String: Int] = [
        "PLAYERANIMEVENT_ATTACK_PRIMARY": 0,
        "PLAYERANIMEVENT_ATTACK_SECONDARY": 1,
        "PLAYERANIMEVENT_ATTACK_GRENADE": 2,
        "PLAYERANIMEVENT_RELOAD": 3,
        "PLAYERANIMEVENT_RELOAD_LOOP": 4,
        "PLAYERANIMEVENT_RELOAD_END": 5,
        "PLAYERANIMEVENT_JUMP": 6,
        "PLAYERANIMEVENT_SWIM": 7,
        "PLAYERANIMEVENT_DIE": 8,
        "PLAYERANIMEVENT_FLINCH_CHEST": 9,
        "PLAYERANIMEVENT_FLINCH_HEAD": 10,
        "PLAYERANIMEVENT_FLINCH_LEFTARM": 11,
        "PLAYERANIMEVENT_FLINCH_RIGHTARM": 12,
        "PLAYERANIMEVENT_FLINCH_LEFTLEG": 13,
        "PLAYERANIMEVENT_FLINCH_RIGHTLEG": 14,
        "PLAYERANIMEVENT_DOUBLEJUMP": 15,
        "PLAYERANIMEVENT_CANCEL": 16,
        "PLAYERANIMEVENT_SPAWN": 17,
        "PLAYERANIMEVENT_SNAP_YAW": 18,
        "PLAYERANIMEVENT_CUSTOM": 19,
        "PLAYERANIMEVENT_CUSTOM_GESTURE": 20,
        "PLAYERANIMEVENT_CUSTOM_SEQUENCE": 21,
        "PLAYERANIMEVENT_CUSTOM_GESTURE_SEQUENCE": 22,
        "PLAYERANIMEVENT_CANCEL_RELOAD": 23
    ]

    public static let gestureSlotConstants: [String: Int] = [
        "GESTURE_SLOT_ATTACK_AND_RELOAD": 0,
        "GESTURE_SLOT_GRENADE": 1,
        "GESTURE_SLOT_JUMP": 2,
        "GESTURE_SLOT_SWIM": 3,
        "GESTURE_SLOT_FLINCH": 4,
        "GESTURE_SLOT_VCD": 5,
        "GESTURE_SLOT_CUSTOM": 6
    ]

    /// Two engine flags used directly by Base's animation dispatcher. The
    /// broader FL and MOVETYPE families belong to their respective engine API
    /// milestones and are not represented as complete here.
    public static let relatedEngineConstants: [String: Int] = [
        "FL_ANIMDUCKING": 4,
        "MOVETYPE_NOCLIP": 8
    ]

    public static var installedConstants: [String: Int] {
        activityConstantsRequiredByBundledGamemodes
            .merging(playerConstants) { _, rhs in rhs }
            .merging(playerAnimationEventConstants) { _, rhs in rhs }
            .merging(gestureSlotConstants) { _, rhs in rhs }
            .merging(relatedEngineConstants) { _, rhs in rhs }
    }

    public static func install(into state: LuaState) {
        for (name, value) in installedConstants {
            state.setGlobal(name, value: .number(Double(value)))
        }
    }
}
